
from flask import Flask, render_template, request

app = Flask(__name__)


import os
import requests
from dotenv import load_dotenv


load_dotenv()


IBM_API_KEY = os.getenv("IBM_API_KEY")



def generate_story(prompt, genre, tone):


    """
    IBM Granite AI generation function.
    """



    if not IBM_API_KEY:

        return """
        Demo Mode

        IBM Granite API key not configured.

        Sample AI Output:

        Title:
        The Future Creator

        Summary:
        A new story generated by AI.

        """


    url = "YOUR_GRANITE_ENDPOINT"


    headers = {

        "Authorization":
        f"Bearer {IBM_API_KEY}",

        "Content-Type":
        "application/json"

    }



    data = {

        "input":
        f"""
        Create a creative story.

        Idea:
        {prompt}

        Genre:
        {genre}

        Tone:
        {tone}

        Include:
        - title
        - summary
        - characters
        - ending

        """

    }



    response = requests.post(

        url,

        headers=headers,

        json=data

    )



    result = response.json()



    return result["generated_text"]

if __name__ == "__main__":
    app.run(debug=True)
